### ISSUE TITLE
Bug: Drag and Drop is flawed on Firefox

### ISSUE THREAD

**Issue by jwanner83** [octokatherine/readme.so#256]
**Describe the bug**
When I want to drag and drop the sections on the left side when using Firefox, the behavior is really weird.

**To Reproduce**
1. Open https://readme.so/en/editor on Firefox 
2. Try to drag and drop the sections.

**Expected behavior**
The drag and drop should work as expected.

**Screenshots**
https://user-images.githubusercontent.com/38656104/185174618-71e5b31f-fecb-4b8c-be5e-401122a7a9c2.mov

**Additional context**
Firefox Version: 103.0.2 (64-Bit)
MacOS Monterey Version: 12.3.1 (21E258)

**Comment by AlperBayraktar** [comment]
I downloaded Firefox 104.0.1 (64-Bit), cloned the project and saw the same problem. I tried to update dnd-kit

**Comment by AlperBayraktar** [comment]
Same problem with Firefox 104.0.1 (64-Bit, latest version). I tried to update dnd-kit packages (dnd-kit/core, dnd-kit/modifiers, dnd-kit/sortable) with `npm update @dnd-kit/core @dnd-kit/modifiers @dnd-kit/sortable --dd` command and got an output like this:

> npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'update',
npm verb cli   '@dnd-kit/core',
npm verb cli   '@dnd-kit/modifiers',
npm verb cli   '@dnd-kit/sortable',
npm verb cli   '--dd'
npm verb cli ]
npm info using npm@6.14.13
npm info using node@v14.17.0
npm verb npm-session 46f3f8b1d04c9f8f
npm verb update computing outdated modules to update
npm http fetch GET 304 https://registry.npmjs.org/@dnd-kit%2fsortable 612ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@dnd-kit%2fmodifiers 616ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@dnd-kit%2fcore 672ms (from cache)
npm verb outdated not updating @dnd-kit/core because it's currently at the maximum version that matches its specified semver range     
npm verb outdated not updating @dnd-kit/modifiers because it's currently at the maximum version that matches its specified semver range
npm verb outdated not updating @dnd-kit/sortable because it's currently at the maximum version that matches its specified semver range 
npm verb exit [ 0, true ]
npm timing npm Completed in 4719ms
npm info ok

Can't update because of its specified semver range:

> npm verb outdated not updating @dnd-kit/core because it's currently at the maximum version that matches its specified semver range
npm verb outdated not updating @dnd-kit/modifiers because it's currently at the maximum version that matches its specified semver range
npm verb outdated not updating @dnd-kit/sortable because it's currently at the maximum version that matches its specified semver range

So i updated package.json

from this:
> "@dnd-kit/core": "^2.1.2",
    "@dnd-kit/modifiers": "^1.0.5",
    "@dnd-kit/sortable": "^2.0.1",

to this:

> "@dnd-kit/core": ">=2.1.2",
    "@dnd-kit/modifiers": ">=1.0.5",
    "@dnd-kit/sortable": ">=2.0.1",

After running the same command, package versions become the latest and problem was solved.
